// <auto-generated />
using System;
using ConfigAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210428142102_togBortCollectionsParents")]
    partial class togBortCollectionsParents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ConfigAPI.Model.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerPartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("ConfigAPI.Model.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ConfigAPI.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ConfigAPI.Model.Component", b =>
                {
                    b.HasOne("ConfigAPI.Model.Item", null)
                        .WithMany("Components")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("ConfigAPI.Model.Item", b =>
                {
                    b.HasOne("ConfigAPI.Model.Configuration", null)
                        .WithMany("Items")
                        .HasForeignKey("ConfigurationId");
                });

            modelBuilder.Entity("ConfigAPI.Model.Configuration", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ConfigAPI.Model.Item", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
